POST http://localhost:6001/api/phonebill/ HTTP/1.1
content-type: application/json

{
    "price_plan": "sms_kick_100",
    "actions" : "call, sms, call"
}

###
POST  http://LOCALHOST:6001/api/phonebill/
content-type: application/json

{
    "price_plan": "sms 101",
    "actions" : "calls, sms, call"
}

###

GET http://localhost:6001/api/price_plans

###

POST http://localhost:6001/api/price_plan/update
content-type: application/json

//Send in the price plan data to update:

{
    "name": "mahala haa",
    "call_cost" : 0,
    "sms_cost": 0
}

###

POST /api/price_plan/delete Delete a price plan
Content-Type: application/json

//Input - the price plan to delete

{
    "id: 17"
}


###

POST http://localhost:6001/api/price_plan/delete
content-type: application/json

{
    "plan_name": "2cents"
}


###

POST http://localhost:6001/api/price_plan/add
content-type: application/json

{
    "plan_name": "2cents",
    "sms_price": 20,
    "call_price": 30
}